name: publish-dockerhub
on:
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set release version env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    - name: Publish with tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ secrets.DOCKERHUB_USER }}/blaezi:${{ env.RELEASE_VERSION }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        dockerfile: Dockerfile
        cache: false
        
    - name: Publish latest
      if: "!startsWith(github.ref, 'refs/tags/v')"
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ secrets.DOCKERHUB_USER }}/blaezi:latest
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        dockerfile: Dockerfile
        cache: false